server:
  port: 8080
spring:
  application:
    name: upvote-public-service
zuul:
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
  ribbon:
    eager-load:
      enabled: false
  routes:
    upvote-auth-service:
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
      url: http://user:8087/
    upvote-user-service:
      sensitiveHeaders:
      path: /users/**
      stripPrefix: true
      url: http://user:8087/
    upvote-achievement-service:
      sensitiveHeaders:
      path: /achievements/**
      stripPrefix: true
      url: http://achievement:8083/
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
