server:
  port: 8080
spring:
  application:
    name: upvote-public-service
zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    upvote-user-service:
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
      serviceId: upvote-user-service
    upvote-achievement-service:
      sensitiveHeaders:
      path: /achievements/**
      stripPrefix: false
      serviceId: upvote-achievement-service
