server:
  port: 8080
spring:
  application:
    name: upvote-public-service
zuul:
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
  ribbon:
    eager-load:
      enabled: false
  routes:
    upvote-auth-service:
      sensitiveHeaders:
      path: /auth/**
      stripPrefix: false
      url: http://user:8087/
    upvote-profile-service:
      sensitiveHeaders:
      path: /profiles/**
      stripPrefix: false
      url: http://user:8087/
    upvote-settings-service:
      sensitiveHeaders:
      path: /settings/**
      stripPrefix: false
      url: http://user:8087/
    upvote-achievement-service:
      sensitiveHeaders:
      path: /achievements/**
      stripPrefix: false
      url: http://achievement:8083/
    upvote-notification-service:
      sensitiveHeaders:
      path: /notifications/**
      stripPrefix: false
      url: http://notifiction:8085/
    upvote-blog-service:
      sensitiveHeaders:
      path: /blogs/**
      stripPrefix: false
      url: http://blog:8082/
    upvote-post-service:
      sensitiveHeaders:
      path: /posts/**
      stripPrefix: false
      url: http://post:8081/
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
